# Generated by Django 5.2 on 2025-04-21 07:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='COURSE',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('des_teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'COURSE',
            },
        ),
        migrations.CreateModel(
            name='DOCUMENT',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'db_table': 'DOCUMENT',
            },
        ),
        migrations.CreateModel(
            name='QUESTION_MEDIA',
            fields=[
                ('questionmedia_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_file', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
            ],
            options={
                'db_table': 'QUESTION_MEDIA',
            },
        ),
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('test_description', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.TimeField()),
            ],
            options={
                'db_table': 'TEST',
            },
        ),
        migrations.CreateModel(
            name='CLASS',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('begin_time', models.DateField()),
                ('end_time', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('timetable', models.CharField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.course')),
            ],
            options={
                'db_table': 'CLASS',
            },
        ),
        migrations.CreateModel(
            name='LESSON',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_file', models.FileField(upload_to='')),
                ('exercise_file', models.FileField(upload_to='')),
                ('lesson_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.course')),
            ],
            options={
                'db_table': 'LESSON',
            },
        ),
        migrations.CreateModel(
            name='LESSON_DETAIL',
            fields=[
                ('lessondetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_number', models.CharField(max_length=100, null=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.class')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.lesson')),
            ],
            options={
                'db_table': 'LessonDetail',
            },
        ),
        migrations.CreateModel(
            name='EXERCISE',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('duedate', models.DateField()),
                ('lessondetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='english.lesson_detail')),
            ],
            options={
                'db_table': 'EXERCISE',
            },
        ),
        migrations.CreateModel(
            name='PAYMENT',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('qr', models.CharField(blank=True, max_length=100, null=True)),
                ('account_owner', models.CharField(max_length=100, null=True)),
                ('account_number', models.CharField(max_length=100, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.course')),
            ],
            options={
                'db_table': 'PAYMENT',
            },
        ),
        migrations.CreateModel(
            name='PAYMENT_INFO',
            fields=[
                ('paymentinfo_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_at', models.DateTimeField(default=datetime.datetime(2025, 4, 21, 14, 29, 30, 673234))),
                ('message', models.CharField(max_length=150)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ROLLCALL',
            fields=[
                ('rollcall_id', models.AutoField(primary_key=True, serialize=False)),
                ('lessondetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='english.lesson_detail')),
            ],
            options={
                'db_table': 'ROLL_CALL',
            },
        ),
        migrations.CreateModel(
            name='RESULT',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.test')),
            ],
            options={
                'db_table': 'RESULT',
            },
        ),
        migrations.CreateModel(
            name='QUESTION',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=50, null=True)),
                ('question_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.question_media')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.test')),
            ],
            options={
                'db_table': 'QUESTION',
            },
        ),
        migrations.CreateModel(
            name='USER_CLASS',
            fields=[
                ('userclass_id', models.AutoField(primary_key=True, serialize=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_CLASS',
            },
        ),
        migrations.CreateModel(
            name='SUBMISSION',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('done', 'Done'), ('check', 'Check')], max_length=50)),
                ('submit_date', models.DateTimeField(default=datetime.datetime(2025, 4, 21, 14, 29, 30, 673234))),
                ('review', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.exercise')),
                ('userclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.user_class')),
            ],
            options={
                'db_table': 'SUBMISSION',
            },
        ),
        migrations.CreateModel(
            name='ROLLCALL_USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=100)),
                ('rollcall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.rollcall')),
                ('userclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.user_class')),
            ],
            options={
                'db_table': 'ROLL_CALL_USER',
            },
        ),
        migrations.CreateModel(
            name='USER_PROFILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(max_length=100)),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_PROFILE',
            },
        ),
    ]
