# Generated by Django 5.1.4 on 2025-04-06 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
            ],
            options={
                'db_table': 'ACCOUNT',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('des_teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'COURSE',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_file', models.BinaryField(null=True)),
            ],
            options={
                'db_table': 'DOCUMENT',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('test_description', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'TEST',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('begin_time', models.DateField()),
                ('end_time', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.course')),
            ],
            options={
                'db_table': 'CLASS',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('lesson_file', models.CharField(blank=True, max_length=255, null=True)),
                ('exercise_file', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.course')),
            ],
            options={
                'db_table': 'LESSON',
            },
        ),
        migrations.CreateModel(
            name='LessonDetail',
            fields=[
                ('lessonDetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.class')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.lesson')),
            ],
            options={
                'db_table': 'LessonDetail',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('duedate', models.DateField()),
                ('lesson_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.lessondetail')),
            ],
            options={
                'db_table': 'EXERCISE',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('qr', models.BinaryField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.course')),
            ],
            options={
                'db_table': 'PAYMENT',
            },
        ),
        migrations.CreateModel(
            name='RollCall',
            fields=[
                ('rollcall_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.lessondetail')),
            ],
            options={
                'db_table': 'ROLL_CALL',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=50, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.test')),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('userclass_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.class')),
            ],
            options={
                'db_table': 'USER_CLASS',
            },
        ),
        migrations.CreateModel(
            name='RollCallUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollcall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.rollcall')),
                ('userclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.userclass')),
            ],
            options={
                'db_table': 'ROLL_CALL_USER',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.account')),
            ],
            options={
                'db_table': 'USER_PROFILE',
            },
        ),
        migrations.AddField(
            model_name='userclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.userprofile'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('done', 'Done'), ('check', 'Check')], max_length=50)),
                ('submit_date', models.DateField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.userprofile')),
            ],
            options={
                'db_table': 'SUBMISSION',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.userprofile')),
            ],
            options={
                'db_table': 'RESULT',
            },
        ),
    ]
