# Generated by Django 5.1.4 on 2025-04-18 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='time_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 14, 20, 55, 795685)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 14, 20, 55, 796660)),
        ),
    ]
