# Generated by Django 5.2 on 2025-04-18 04:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USER_PROFILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_PROFILE',
            },
        ),
        migrations.DeleteModel(
            name='ACCOUNT',
        ),
        migrations.AlterField(
            model_name='lesson_detail',
            name='session_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='time_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 11, 48, 21, 726314)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 11, 48, 21, 726314)),
        ),
    ]
