# Generated by Django 5.2 on 2025-04-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
