# Generated by Django 5.1.4 on 2025-04-21 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_alter_payment_info_time_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='time_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 9, 55, 30, 413429)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 9, 55, 30, 414469)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
