# Generated by Django 5.2 on 2025-04-20 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_alter_payment_info_time_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='time_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 21, 33, 17, 507313)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 21, 33, 17, 509319)),
        ),
    ]
