# Generated by Django 5.2 on 2025-05-19 08:38

import datetime
import django.db.models.deletion
import english.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_payment_info_time_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission_file_name',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_file_type',
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='time_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 15, 38, 44, 64516)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_file_content',
            field=models.FileField(blank=True, null=True, upload_to=english.models.submission_upload_path),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
