# Generated by Django 5.1.4 on 2025-04-21 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_payment_info_time_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='reset_password_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='time_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 10, 3, 22, 110050)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 10, 3, 22, 112427)),
        ),
    ]
